openapi: 3.1.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
info:
  title: Codescan MVP API
  version: 0.1.0
  description: Minimal 3.1 spec used to validate MVP emission (paths, requestBody, responses, schemas).
servers:
  - url: https://api.example.com/v1
paths:
  /health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    const: healthy
  /items:
    post:
      summary: Create item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItem'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: List items
      operationId: listItems
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 1
        description:
          type: [string, 'null']
    NewItem:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: [string, 'null']
    Error:
      type: object
      required: [message]
      properties:
        message:
          type: string
