// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubReactions github reactions
//
// swagger:model github.Reactions
type GithubReactions struct {

	// 1
	Plus1 int64 `json:"+1,omitempty"`

	// 1
	Minus1 int64 `json:"-1,omitempty"`

	// confused
	Confused int64 `json:"confused,omitempty"`
}

// Validate validates this github reactions
func (m *GithubReactions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github reactions based on context it is used
func (m *GithubReactions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubReactions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubReactions) UnmarshalBinary(b []byte) error {
	var res GithubReactions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
