linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

run:
  skip-dirs:
    - playground

linters:
  enable:
    - golint
    - gocritic
    - stylecheck
    # - goimports
    - gosec
    - nakedret
    - unconvert
    - unparam
  disable:
    - maligned
    - unparam
    - lll
    - gochecknoinits
    - gochecknoglobals
    - dupl
