linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: github.com/pkg/errors
            desc: "Use errors or fmt instead of github.com/pkg/errors"
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 25
  goimports:
    local-prefixes: github.com/go-swagger/go-swagger
  govet:
    enable: ["shadow"]
  # golint:
  #   min-confidence: 0
  # govet:
  #   check-shadowing: true
  # maligned:
  #   suggest-new: true
  testifylint:
    disable:
      - float-compare
      - go-require
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - len
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call

issues:
  exclude-dirs:
    - playground
    - fixtures
    - cmd
run:
  timeout: 5m

linters:
  enable:
    - depguard
    - errorlint
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - misspell
    - revive
    - stylecheck
    - testifylint
    - unconvert
    - govet
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - lll
    - nakedret
    - unparam
