version: "2"
linters:
  enable:
    - depguard
    - errorlint
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - lll
    - nakedret
    - unparam
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: github.com/pkg/errors
              desc: Use errors or fmt instead of github.com/pkg/errors
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 25
    govet:
      enable-all: true
      disable:
        - fieldalignment
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - len
        - require-error
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - float-compare
        - go-require
  exclusions:
    warn-unused: false
    generated: disable  # enable linting on generated code (in examples, in generated code under test)
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - fixtures/
      - examples/
    rules:
      # do not exclude examples from linting, but apply slightly different rules
      - path: examples/
        linters:
          - gofumpt # we don't run gofumpt on generated examples, only goimports
      - path: 'generator/generated/'
        linters:
          - gofumpt # we don't run gofumpt on generated code (used during testing)
      - path: _test.go
        linters:
          - unparam
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    # local prefixes regroup imports from these packages
    goimports:
      local-prefixes:
        - github.com/go-openapi
        - github.com/go-swagger/go-swagger # this is for imports in generated examples
  exclusions:
    # do not exclude examples from linting
    paths:
      - fixtures/
