version: "2"
linters:
  enable:
    - depguard
    - errorlint
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - lll
    - nakedret
    - unparam
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: github.com/pkg/errors
              desc: Use errors or fmt instead of github.com/pkg/errors
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 25
    govet:
      enable-all: true
      disable:
        - fieldalignment
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - len
        - require-error
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - float-compare
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - fixtures/
      - examples/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/go-swagger/go-swagger
  exclusions:
    generated: lax
    paths:
      - fixtures/
      - examples/
