FROM golang@sha256:672a2286da3ee7a854c3e0a56e0838918d0dbb1c18652992930293312de898a6

COPY hack/devtools.sh /opt/devtools.sh

# install the devtools; keeping them in original script will
# enable local development w/o Docker if desired.
RUN set -e -x \
    && /opt/devtools.sh

ENV CGO_ENABLED 1
ENV GOPATH /go:/go-swagger
