package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*PostEventCreated Successful response.
'Location' header with link to /events/{id} containing new ID.


swagger:response postEventCreated
*/
type PostEventCreated struct {
}

// WriteResponse to the client
func (o *PostEventCreated) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(201)
}

/*PostEventDefault Generic Error

swagger:response postEventDefault
*/
type PostEventDefault struct {
}

// WriteResponse to the client
func (o *PostEventDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
}
