
// Copyright 2015 go-swagger maintainers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// PutEventByIDHandlerFunc turns a function with the right signature into a put event by id handler
type PutEventByIDHandlerFunc func(PutEventByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutEventByIDHandlerFunc) Handle(params PutEventByIDParams) middleware.Responder {
	return fn(params)
}

// PutEventByIDHandler interface for that can handle valid put event by id params
type PutEventByIDHandler interface {
	Handle(PutEventByIDParams) middleware.Responder
}

// NewPutEventByID creates a new http.Handler for the put event by id operation
func NewPutEventByID(ctx *middleware.Context, handler PutEventByIDHandler) *PutEventByID {
	return &PutEventByID{Context: ctx, Handler: handler}
}

/*
Update existing event.
*/
type PutEventByID struct {
	Context *middleware.Context
	Params  PutEventByIDParams
	Handler PutEventByIDHandler
}

func (o *PutEventByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(o.Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
