// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/go-swagger/go-swagger/examples/authentication/models"
)

// GetIDReader is a Reader for the GetID structure.
type GetIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetIDOK creates a GetIDOK with default headers values
func NewGetIDOK() *GetIDOK {
	return &GetIDOK{}
}

/*GetIDOK handles this case with default header values.

OK
*/
type GetIDOK struct {
	Payload *models.Customer
}

func (o *GetIDOK) Error() string {
	return fmt.Sprintf("[GET /customers][%d] getIdOK  %+v", 200, o.Payload)
}

func (o *GetIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Customer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIDUnauthorized creates a GetIDUnauthorized with default headers values
func NewGetIDUnauthorized() *GetIDUnauthorized {
	return &GetIDUnauthorized{}
}

/*GetIDUnauthorized handles this case with default header values.

unauthorized
*/
type GetIDUnauthorized struct {
	Payload *models.Error
}

func (o *GetIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /customers][%d] getIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIDNotFound creates a GetIDNotFound with default headers values
func NewGetIDNotFound() *GetIDNotFound {
	return &GetIDNotFound{}
}

/*GetIDNotFound handles this case with default header values.

resource not found
*/
type GetIDNotFound struct {
	Payload *models.Error
}

func (o *GetIDNotFound) Error() string {
	return fmt.Sprintf("[GET /customers][%d] getIdNotFound  %+v", 404, o.Payload)
}

func (o *GetIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIDDefault creates a GetIDDefault with default headers values
func NewGetIDDefault(code int) *GetIDDefault {
	return &GetIDDefault{
		_statusCode: code,
	}
}

/*GetIDDefault handles this case with default header values.

error
*/
type GetIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get Id default response
func (o *GetIDDefault) Code() int {
	return o._statusCode
}

func (o *GetIDDefault) Error() string {
	return fmt.Sprintf("[GET /customers][%d] getId default  %+v", o._statusCode, o.Payload)
}

func (o *GetIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
