// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTodosTodoIDHandlerFunc turns a function with the right signature into a get todos todo ID handler
type GetTodosTodoIDHandlerFunc func(GetTodosTodoIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTodosTodoIDHandlerFunc) Handle(params GetTodosTodoIDParams) middleware.Responder {
	return fn(params)
}

// GetTodosTodoIDHandler interface for that can handle valid get todos todo ID params
type GetTodosTodoIDHandler interface {
	Handle(GetTodosTodoIDParams) middleware.Responder
}

// NewGetTodosTodoID creates a new http.Handler for the get todos todo ID operation
func NewGetTodosTodoID(ctx *middleware.Context, handler GetTodosTodoIDHandler) *GetTodosTodoID {
	return &GetTodosTodoID{Context: ctx, Handler: handler}
}

/*
	GetTodosTodoID swagger:route GET /todos/{todoId} Todos getTodosTodoId

Get Todo
*/
type GetTodosTodoID struct {
	Context *middleware.Context
	Handler GetTodosTodoIDHandler
}

func (o *GetTodosTodoID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTodosTodoIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
