// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutTodosTodoIDHandlerFunc turns a function with the right signature into a put todos todo ID handler
type PutTodosTodoIDHandlerFunc func(PutTodosTodoIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTodosTodoIDHandlerFunc) Handle(params PutTodosTodoIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutTodosTodoIDHandler interface for that can handle valid put todos todo ID params
type PutTodosTodoIDHandler interface {
	Handle(PutTodosTodoIDParams, interface{}) middleware.Responder
}

// NewPutTodosTodoID creates a new http.Handler for the put todos todo ID operation
func NewPutTodosTodoID(ctx *middleware.Context, handler PutTodosTodoIDHandler) *PutTodosTodoID {
	return &PutTodosTodoID{Context: ctx, Handler: handler}
}

/*
	PutTodosTodoID swagger:route PUT /todos/{todoId} Todos putTodosTodoId

Update Todo
*/
type PutTodosTodoID struct {
	Context *middleware.Context
	Handler PutTodosTodoIDHandler
}

func (o *PutTodosTodoID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTodosTodoIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
