// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/examples/cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for Error

// register flags to command
func registerModelErrorFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerErrorCode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerErrorMessage(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerErrorCode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	CodeDescription := ``

	var CodeFlagName string
	if cmdPrefix == "" {
		CodeFlagName = "code"
	} else {
		CodeFlagName = fmt.Sprintf("%v.code", cmdPrefix)
	}

	var CodeFlagDefault int64

	_ = cmd.PersistentFlags().Int64(CodeFlagName, CodeFlagDefault, CodeDescription)

	return nil
}

func registerErrorMessage(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	MessageDescription := `Required. `

	var MessageFlagName string
	if cmdPrefix == "" {
		MessageFlagName = "message"
	} else {
		MessageFlagName = fmt.Sprintf("%v.message", cmdPrefix)
	}

	var MessageFlagDefault string

	_ = cmd.PersistentFlags().String(MessageFlagName, MessageFlagDefault, MessageDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelErrorFlags(depth int, m *models.Error, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CodeAdded := retrieveErrorCodeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CodeAdded

	err, MessageAdded := retrieveErrorMessageFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MessageAdded

	return nil, retAdded
}

func retrieveErrorCodeFlags(depth int, m *models.Error, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	CodeFlagName := fmt.Sprintf("%v.code", cmdPrefix)
	if cmd.Flags().Changed(CodeFlagName) {

		var CodeFlagName string
		if cmdPrefix == "" {
			CodeFlagName = "code"
		} else {
			CodeFlagName = fmt.Sprintf("%v.code", cmdPrefix)
		}

		CodeFlagValue, err := cmd.Flags().GetInt64(CodeFlagName)
		if err != nil {
			return err, false
		}
		m.Code = CodeFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveErrorMessageFlags(depth int, m *models.Error, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	MessageFlagName := fmt.Sprintf("%v.message", cmdPrefix)
	if cmd.Flags().Changed(MessageFlagName) {

		var MessageFlagName string
		if cmdPrefix == "" {
			MessageFlagName = "message"
		} else {
			MessageFlagName = fmt.Sprintf("%v.message", cmdPrefix)
		}

		MessageFlagValue, err := cmd.Flags().GetString(MessageFlagName)
		if err != nil {
			return err, false
		}
		m.Message = &MessageFlagValue

		retAdded = true
	}

	return nil, retAdded
}
