// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/examples/cli/models"
	"github.com/spf13/cobra"
)

// register flags to command
func registerItemFlags(cmdPrefix string, cmd *cobra.Command) error {

	if err := registerItemCompleted(cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerItemDescription(cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerItemID(cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerItemCompleted(cmdPrefix string, cmd *cobra.Command) error {

	completedDescription := ``

	var completedFlagName string
	if cmdPrefix == "" {
		completedFlagName = "completed"
	} else {
		completedFlagName = fmt.Sprintf("%v.completed", cmdPrefix)
	}

	var completedFlagDefault bool

	_ = cmd.PersistentFlags().Bool(completedFlagName, completedFlagDefault, completedDescription)

	return nil
}

func registerItemDescription(cmdPrefix string, cmd *cobra.Command) error {

	descriptionDescription := `Required. `

	var descriptionFlagName string
	if cmdPrefix == "" {
		descriptionFlagName = "description"
	} else {
		descriptionFlagName = fmt.Sprintf("%v.description", cmdPrefix)
	}

	var descriptionFlagDefault string

	_ = cmd.PersistentFlags().String(descriptionFlagName, descriptionFlagDefault, descriptionDescription)

	if err := cmd.MarkPersistentFlagRequired(descriptionFlagName); err != nil {
		return err
	}

	return nil
}

func registerItemID(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := ``

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveItemFlags(m *models.Item, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, completedAdded := retrieveItemCompletedFlags(m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || completedAdded

	err, descriptionAdded := retrieveItemDescriptionFlags(m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || descriptionAdded

	err, idAdded := retrieveItemIDFlags(m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || idAdded

	return nil, retAdded
}

func retrieveItemCompletedFlags(m *models.Item, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	completedFlagName := fmt.Sprintf("%v.completed", cmdPrefix)
	if cmd.Flags().Changed(completedFlagName) {

		var completedFlagName string
		if cmdPrefix == "" {
			completedFlagName = "completed"
		} else {
			completedFlagName = fmt.Sprintf("%v.completed", cmdPrefix)
		}

		completedFlagValue, err := cmd.Flags().GetBool(completedFlagName)
		if err != nil {
			return err, false
		}
		m.Completed = completedFlagValue

		retAdded = true
	}
	return nil, retAdded
}

func retrieveItemDescriptionFlags(m *models.Item, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	descriptionFlagName := fmt.Sprintf("%v.description", cmdPrefix)
	if cmd.Flags().Changed(descriptionFlagName) {

		var descriptionFlagName string
		if cmdPrefix == "" {
			descriptionFlagName = "description"
		} else {
			descriptionFlagName = fmt.Sprintf("%v.description", cmdPrefix)
		}

		descriptionFlagValue, err := cmd.Flags().GetString(descriptionFlagName)
		if err != nil {
			return err, false
		}
		m.Description = &descriptionFlagValue

		retAdded = true
	}
	return nil, retAdded
}

func retrieveItemIDFlags(m *models.Item, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	idFlagName := fmt.Sprintf("%v.id", cmdPrefix)
	if cmd.Flags().Changed(idFlagName) {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

		retAdded = true
	}
	return nil, retAdded
}
