// Code generated by go-swagger; DO NOT EDIT.

package models2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ExtUserObjectRef user object ref
// swagger:model ExtUserObjectRef
type ExtUserObjectRef struct {
	ExtUser
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExtUserObjectRef) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ExtUser
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ExtUser = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExtUserObjectRef) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ExtUser)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this user object ref
func (m *ExtUserObjectRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtUserObjectRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtUserObjectRef) UnmarshalBinary(b []byte) error {
	var res ExtUserObjectRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
