FROM golang:latest@sha256:8c945d3e25320e771326dafc6fb72ecae5f87b0f29328cbbd87c4dff506c9135

COPY hack/devtools.sh /opt/devtools.sh

# install the devtools; keeping them in original script will
# enable local development w/o Docker if desired.
RUN set -e -x \
    && /opt/devtools.sh

ENV CGO_ENABLED 1
ENV GOPATH /go:/go-swagger
