// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2969/codegen/client/artifacts"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationArtifactsDeleteArtifactOfVersionCmd returns a command to handle operation deleteArtifactOfVersion
func makeOperationArtifactsDeleteArtifactOfVersionCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteArtifactOfVersion",
		Short: `Delete Artifact of a specified version`,
		RunE:  runOperationArtifactsDeleteArtifactOfVersion,
	}

	if err := registerOperationArtifactsDeleteArtifactOfVersionParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationArtifactsDeleteArtifactOfVersion uses cmd flags to call endpoint api
func runOperationArtifactsDeleteArtifactOfVersion(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := artifacts.NewDeleteArtifactOfVersionParams()
	if err, _ = retrieveOperationArtifactsDeleteArtifactOfVersionIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationArtifactsDeleteArtifactOfVersionVersionFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationArtifactsDeleteArtifactOfVersionResult(appCli.Artifacts.DeleteArtifactOfVersion(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationArtifactsDeleteArtifactOfVersionParamFlags registers all flags needed to fill params
func registerOperationArtifactsDeleteArtifactOfVersionParamFlags(cmd *cobra.Command) error {
	if err := registerOperationArtifactsDeleteArtifactOfVersionIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactsDeleteArtifactOfVersionVersionParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationArtifactsDeleteArtifactOfVersionIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. artifact id`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func registerOperationArtifactsDeleteArtifactOfVersionVersionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	versionDescription := `Required. artifact version`

	var versionFlagName string
	if cmdPrefix == "" {
		versionFlagName = "version"
	} else {
		versionFlagName = fmt.Sprintf("%v.version", cmdPrefix)
	}

	var versionFlagDefault string

	_ = cmd.PersistentFlags().String(versionFlagName, versionFlagDefault, versionDescription)

	return nil
}

func retrieveOperationArtifactsDeleteArtifactOfVersionIDFlag(m *artifacts.DeleteArtifactOfVersionParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}

	return nil, retAdded
}

func retrieveOperationArtifactsDeleteArtifactOfVersionVersionFlag(m *artifacts.DeleteArtifactOfVersionParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("version") {

		var versionFlagName string
		if cmdPrefix == "" {
			versionFlagName = "version"
		} else {
			versionFlagName = fmt.Sprintf("%v.version", cmdPrefix)
		}

		versionFlagValue, err := cmd.Flags().GetString(versionFlagName)
		if err != nil {
			return err, false
		}
		m.Version = versionFlagValue

	}

	return nil, retAdded
}

// parseOperationArtifactsDeleteArtifactOfVersionResult parses request result and return the string content
func parseOperationArtifactsDeleteArtifactOfVersionResult(resp0 *artifacts.DeleteArtifactOfVersionNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning deleteArtifactOfVersionNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*artifacts.DeleteArtifactOfVersionBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*artifacts.DeleteArtifactOfVersionUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*artifacts.DeleteArtifactOfVersionForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*artifacts.DeleteArtifactOfVersionNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*artifacts.DeleteArtifactOfVersionConflict)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp6 interface{} = respErr
		resp6, ok := iResp6.(*artifacts.DeleteArtifactOfVersionInternalServerError)
		if ok {
			if !swag.IsZero(resp6) && !swag.IsZero(resp6.Payload) {
				msgStr, err := json.Marshal(resp6.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response deleteArtifactOfVersionNoContent is not supported by go-swagger cli yet.

	return "", nil
}
