// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2969/codegen/client/resources"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationResourcesDeleteResourceCmd returns a command to handle operation deleteResource
func makeOperationResourcesDeleteResourceCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteResource",
		Short: ``,
		RunE:  runOperationResourcesDeleteResource,
	}

	if err := registerOperationResourcesDeleteResourceParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationResourcesDeleteResource uses cmd flags to call endpoint api
func runOperationResourcesDeleteResource(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := resources.NewDeleteResourceParams()
	if err, _ = retrieveOperationResourcesDeleteResourceIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationResourcesDeleteResourceResult(appCli.Resources.DeleteResource(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationResourcesDeleteResourceParamFlags registers all flags needed to fill params
func registerOperationResourcesDeleteResourceParamFlags(cmd *cobra.Command) error {
	if err := registerOperationResourcesDeleteResourceIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationResourcesDeleteResourceIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Resource ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationResourcesDeleteResourceIDFlag(m *resources.DeleteResourceParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}

	return nil, retAdded
}

// parseOperationResourcesDeleteResourceResult parses request result and return the string content
func parseOperationResourcesDeleteResourceResult(resp0 *resources.DeleteResourceNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning deleteResourceNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*resources.DeleteResourceBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*resources.DeleteResourceUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*resources.DeleteResourceForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*resources.DeleteResourceNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*resources.DeleteResourceConflict)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp6 interface{} = respErr
		resp6, ok := iResp6.(*resources.DeleteResourceInternalServerError)
		if ok {
			if !swag.IsZero(resp6) && !swag.IsZero(resp6.Payload) {
				msgStr, err := json.Marshal(resp6.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response deleteResourceNoContent is not supported by go-swagger cli yet.

	return "", nil
}
