// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2969/codegen/client/schedules"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationSchedulesGetAllSchedulesMultipleTriggersCmd returns a command to handle operation getAllSchedulesMultipleTriggers
func makeOperationSchedulesGetAllSchedulesMultipleTriggersCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getAllSchedulesMultipleTriggers",
		Short: ``,
		RunE:  runOperationSchedulesGetAllSchedulesMultipleTriggers,
	}

	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSchedulesGetAllSchedulesMultipleTriggers uses cmd flags to call endpoint api
func runOperationSchedulesGetAllSchedulesMultipleTriggers(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := schedules.NewGetAllSchedulesMultipleTriggersParams()
	if err, _ = retrieveOperationSchedulesGetAllSchedulesMultipleTriggersDescriptionFilterFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSchedulesGetAllSchedulesMultipleTriggersEnvironmentIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSchedulesGetAllSchedulesMultipleTriggersLimitFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSchedulesGetAllSchedulesMultipleTriggersOffsetFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSchedulesGetAllSchedulesMultipleTriggersOnlyBoundFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSchedulesGetAllSchedulesMultipleTriggersResult(appCli.Schedules.GetAllSchedulesMultipleTriggers(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationSchedulesGetAllSchedulesMultipleTriggersParamFlags registers all flags needed to fill params
func registerOperationSchedulesGetAllSchedulesMultipleTriggersParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersDescriptionFilterParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersEnvironmentIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersLimitParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersOffsetParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSchedulesGetAllSchedulesMultipleTriggersOnlyBoundParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSchedulesGetAllSchedulesMultipleTriggersDescriptionFilterParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	descriptionFilterDescription := `Schedulers matching description filter (regular expression)`

	var descriptionFilterFlagName string
	if cmdPrefix == "" {
		descriptionFilterFlagName = "descriptionFilter"
	} else {
		descriptionFilterFlagName = fmt.Sprintf("%v.descriptionFilter", cmdPrefix)
	}

	var descriptionFilterFlagDefault string

	_ = cmd.PersistentFlags().String(descriptionFilterFlagName, descriptionFilterFlagDefault, descriptionFilterDescription)

	return nil
}

func registerOperationSchedulesGetAllSchedulesMultipleTriggersEnvironmentIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	environmentIdDescription := `Schedulers matching environmentId`

	var environmentIdFlagName string
	if cmdPrefix == "" {
		environmentIdFlagName = "environmentId"
	} else {
		environmentIdFlagName = fmt.Sprintf("%v.environmentId", cmdPrefix)
	}

	var environmentIdFlagDefault string

	_ = cmd.PersistentFlags().String(environmentIdFlagName, environmentIdFlagDefault, environmentIdDescription)

	return nil
}

func registerOperationSchedulesGetAllSchedulesMultipleTriggersLimitParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	limitDescription := `the number of items to return. Must be in range [1, 100]. Default value - 100`

	var limitFlagName string
	if cmdPrefix == "" {
		limitFlagName = "limit"
	} else {
		limitFlagName = fmt.Sprintf("%v.limit", cmdPrefix)
	}

	var limitFlagDefault int32

	_ = cmd.PersistentFlags().Int32(limitFlagName, limitFlagDefault, limitDescription)

	return nil
}

func registerOperationSchedulesGetAllSchedulesMultipleTriggersOffsetParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	offsetDescription := `the position of the first item. Must be greater than or equal to 0. Default value - 0`

	var offsetFlagName string
	if cmdPrefix == "" {
		offsetFlagName = "offset"
	} else {
		offsetFlagName = fmt.Sprintf("%v.offset", cmdPrefix)
	}

	var offsetFlagDefault int32

	_ = cmd.PersistentFlags().Int32(offsetFlagName, offsetFlagDefault, offsetDescription)

	return nil
}

func registerOperationSchedulesGetAllSchedulesMultipleTriggersOnlyBoundParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	onlyBoundDescription := `Only bound schedulers`

	var onlyBoundFlagName string
	if cmdPrefix == "" {
		onlyBoundFlagName = "onlyBound"
	} else {
		onlyBoundFlagName = fmt.Sprintf("%v.onlyBound", cmdPrefix)
	}

	var onlyBoundFlagDefault bool

	_ = cmd.PersistentFlags().Bool(onlyBoundFlagName, onlyBoundFlagDefault, onlyBoundDescription)

	return nil
}

func retrieveOperationSchedulesGetAllSchedulesMultipleTriggersDescriptionFilterFlag(m *schedules.GetAllSchedulesMultipleTriggersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("descriptionFilter") {

		var descriptionFilterFlagName string
		if cmdPrefix == "" {
			descriptionFilterFlagName = "descriptionFilter"
		} else {
			descriptionFilterFlagName = fmt.Sprintf("%v.descriptionFilter", cmdPrefix)
		}

		descriptionFilterFlagValue, err := cmd.Flags().GetString(descriptionFilterFlagName)
		if err != nil {
			return err, false
		}
		m.DescriptionFilter = &descriptionFilterFlagValue

	}

	return nil, retAdded
}

func retrieveOperationSchedulesGetAllSchedulesMultipleTriggersEnvironmentIDFlag(m *schedules.GetAllSchedulesMultipleTriggersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("environmentId") {

		var environmentIdFlagName string
		if cmdPrefix == "" {
			environmentIdFlagName = "environmentId"
		} else {
			environmentIdFlagName = fmt.Sprintf("%v.environmentId", cmdPrefix)
		}

		environmentIdFlagValue, err := cmd.Flags().GetString(environmentIdFlagName)
		if err != nil {
			return err, false
		}
		m.EnvironmentID = &environmentIdFlagValue

	}

	return nil, retAdded
}

func retrieveOperationSchedulesGetAllSchedulesMultipleTriggersLimitFlag(m *schedules.GetAllSchedulesMultipleTriggersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("limit") {

		var limitFlagName string
		if cmdPrefix == "" {
			limitFlagName = "limit"
		} else {
			limitFlagName = fmt.Sprintf("%v.limit", cmdPrefix)
		}

		limitFlagValue, err := cmd.Flags().GetInt32(limitFlagName)
		if err != nil {
			return err, false
		}
		m.Limit = &limitFlagValue

	}

	return nil, retAdded
}

func retrieveOperationSchedulesGetAllSchedulesMultipleTriggersOffsetFlag(m *schedules.GetAllSchedulesMultipleTriggersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("offset") {

		var offsetFlagName string
		if cmdPrefix == "" {
			offsetFlagName = "offset"
		} else {
			offsetFlagName = fmt.Sprintf("%v.offset", cmdPrefix)
		}

		offsetFlagValue, err := cmd.Flags().GetInt32(offsetFlagName)
		if err != nil {
			return err, false
		}
		m.Offset = &offsetFlagValue

	}

	return nil, retAdded
}

func retrieveOperationSchedulesGetAllSchedulesMultipleTriggersOnlyBoundFlag(m *schedules.GetAllSchedulesMultipleTriggersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("onlyBound") {

		var onlyBoundFlagName string
		if cmdPrefix == "" {
			onlyBoundFlagName = "onlyBound"
		} else {
			onlyBoundFlagName = fmt.Sprintf("%v.onlyBound", cmdPrefix)
		}

		onlyBoundFlagValue, err := cmd.Flags().GetBool(onlyBoundFlagName)
		if err != nil {
			return err, false
		}
		m.OnlyBound = &onlyBoundFlagValue

	}

	return nil, retAdded
}

// parseOperationSchedulesGetAllSchedulesMultipleTriggersResult parses request result and return the string content
func parseOperationSchedulesGetAllSchedulesMultipleTriggersResult(resp0 *schedules.GetAllSchedulesMultipleTriggersOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*schedules.GetAllSchedulesMultipleTriggersOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*schedules.GetAllSchedulesMultipleTriggersBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*schedules.GetAllSchedulesMultipleTriggersUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*schedules.GetAllSchedulesMultipleTriggersForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*schedules.GetAllSchedulesMultipleTriggersInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
