// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2969/codegen/client/plans_executions"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationPlansExecutionsGetPlanExecutionStatusCmd returns a command to handle operation getPlanExecutionStatus
func makeOperationPlansExecutionsGetPlanExecutionStatusCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getPlanExecutionStatus",
		Short: `Get Plan execution status`,
		RunE:  runOperationPlansExecutionsGetPlanExecutionStatus,
	}

	if err := registerOperationPlansExecutionsGetPlanExecutionStatusParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPlansExecutionsGetPlanExecutionStatus uses cmd flags to call endpoint api
func runOperationPlansExecutionsGetPlanExecutionStatus(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := plans_executions.NewGetPlanExecutionStatusParams()
	if err, _ = retrieveOperationPlansExecutionsGetPlanExecutionStatusIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPlansExecutionsGetPlanExecutionStatusResult(appCli.PlansExecutions.GetPlanExecutionStatus(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationPlansExecutionsGetPlanExecutionStatusParamFlags registers all flags needed to fill params
func registerOperationPlansExecutionsGetPlanExecutionStatusParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPlansExecutionsGetPlanExecutionStatusIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPlansExecutionsGetPlanExecutionStatusIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. execution ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationPlansExecutionsGetPlanExecutionStatusIDFlag(m *plans_executions.GetPlanExecutionStatusParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}

	return nil, retAdded
}

// parseOperationPlansExecutionsGetPlanExecutionStatusResult parses request result and return the string content
func parseOperationPlansExecutionsGetPlanExecutionStatusResult(resp0 *plans_executions.GetPlanExecutionStatusOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*plans_executions.GetPlanExecutionStatusOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*plans_executions.GetPlanExecutionStatusBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*plans_executions.GetPlanExecutionStatusUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*plans_executions.GetPlanExecutionStatusForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*plans_executions.GetPlanExecutionStatusNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*plans_executions.GetPlanExecutionStatusTooManyRequests)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp6 interface{} = respErr
		resp6, ok := iResp6.(*plans_executions.GetPlanExecutionStatusInternalServerError)
		if ok {
			if !swag.IsZero(resp6) && !swag.IsZero(resp6.Payload) {
				msgStr, err := json.Marshal(resp6.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
