// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2969/codegen/client/plans_executables"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationPlansExecutablesStopScheduleForPlanCmd returns a command to handle operation stopScheduleForPlan
func makeOperationPlansExecutablesStopScheduleForPlanCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "stopScheduleForPlan",
		Short: `Stop schedule for plan`,
		RunE:  runOperationPlansExecutablesStopScheduleForPlan,
	}

	if err := registerOperationPlansExecutablesStopScheduleForPlanParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPlansExecutablesStopScheduleForPlan uses cmd flags to call endpoint api
func runOperationPlansExecutablesStopScheduleForPlan(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := plans_executables.NewStopScheduleForPlanParams()
	if err, _ = retrieveOperationPlansExecutablesStopScheduleForPlanPlanIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPlansExecutablesStopScheduleForPlanResult(appCli.PlansExecutables.StopScheduleForPlan(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationPlansExecutablesStopScheduleForPlanParamFlags registers all flags needed to fill params
func registerOperationPlansExecutablesStopScheduleForPlanParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPlansExecutablesStopScheduleForPlanPlanIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPlansExecutablesStopScheduleForPlanPlanIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	planIdDescription := `Required. plan ID`

	var planIdFlagName string
	if cmdPrefix == "" {
		planIdFlagName = "planId"
	} else {
		planIdFlagName = fmt.Sprintf("%v.planId", cmdPrefix)
	}

	var planIdFlagDefault string

	_ = cmd.PersistentFlags().String(planIdFlagName, planIdFlagDefault, planIdDescription)

	return nil
}

func retrieveOperationPlansExecutablesStopScheduleForPlanPlanIDFlag(m *plans_executables.StopScheduleForPlanParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("planId") {

		var planIdFlagName string
		if cmdPrefix == "" {
			planIdFlagName = "planId"
		} else {
			planIdFlagName = fmt.Sprintf("%v.planId", cmdPrefix)
		}

		planIdFlagValue, err := cmd.Flags().GetString(planIdFlagName)
		if err != nil {
			return err, false
		}
		m.PlanID = planIdFlagValue

	}

	return nil, retAdded
}

// parseOperationPlansExecutablesStopScheduleForPlanResult parses request result and return the string content
func parseOperationPlansExecutablesStopScheduleForPlanResult(resp0 *plans_executables.StopScheduleForPlanNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning stopScheduleForPlanNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*plans_executables.StopScheduleForPlanBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*plans_executables.StopScheduleForPlanUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*plans_executables.StopScheduleForPlanForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*plans_executables.StopScheduleForPlanNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*plans_executables.StopScheduleForPlanInternalServerError)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response stopScheduleForPlanNoContent is not supported by go-swagger cli yet.

	return "", nil
}
