openapi: 3.1.0
info:
  title: Widgets API (MVP)
  version: 0.1.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  - url: https://api.example.com/v1
paths:
  /widgets:
    post:
      operationId: createWidget
      summary: Create a widget
      parameters:
        - name: trace
          in: query
          required: false
          description: Optional trace identifier
          schema:
            type: string
            maxLength: 64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWidget'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewWidget:
      type: object
      additionalProperties: false
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        color:
          type: string
          enum: [red, green, blue]
        size:
          type: integer
          minimum: 1
          maximum: 1000
    Widget:
      type: object
      additionalProperties: false
      required: [id, name]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
          enum: [red, green, blue]
        size:
          type: integer
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
