// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTodosTodoIDNoContentCode is the HTTP code returned for type DeleteTodosTodoIDNoContent
const DeleteTodosTodoIDNoContentCode int = 204

/*
DeleteTodosTodoIDNoContent delete todos todo Id no content

swagger:response deleteTodosTodoIdNoContent
*/
type DeleteTodosTodoIDNoContent struct {
}

// NewDeleteTodosTodoIDNoContent creates DeleteTodosTodoIDNoContent with default headers values
func NewDeleteTodosTodoIDNoContent() *DeleteTodosTodoIDNoContent {

	return &DeleteTodosTodoIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteTodosTodoIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteTodosTodoIDUnauthorizedCode is the HTTP code returned for type DeleteTodosTodoIDUnauthorized
const DeleteTodosTodoIDUnauthorizedCode int = 401

/*
DeleteTodosTodoIDUnauthorized delete todos todo Id unauthorized

swagger:response deleteTodosTodoIdUnauthorized
*/
type DeleteTodosTodoIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *DeleteTodosTodoIDUnauthorizedBody `json:"body,omitempty"`
}

// NewDeleteTodosTodoIDUnauthorized creates DeleteTodosTodoIDUnauthorized with default headers values
func NewDeleteTodosTodoIDUnauthorized() *DeleteTodosTodoIDUnauthorized {

	return &DeleteTodosTodoIDUnauthorized{}
}

// WithPayload adds the payload to the delete todos todo Id unauthorized response
func (o *DeleteTodosTodoIDUnauthorized) WithPayload(payload *DeleteTodosTodoIDUnauthorizedBody) *DeleteTodosTodoIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todos todo Id unauthorized response
func (o *DeleteTodosTodoIDUnauthorized) SetPayload(payload *DeleteTodosTodoIDUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodosTodoIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTodosTodoIDNotFoundCode is the HTTP code returned for type DeleteTodosTodoIDNotFound
const DeleteTodosTodoIDNotFoundCode int = 404

/*
DeleteTodosTodoIDNotFound delete todos todo Id not found

swagger:response deleteTodosTodoIdNotFound
*/
type DeleteTodosTodoIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *DeleteTodosTodoIDNotFoundBody `json:"body,omitempty"`
}

// NewDeleteTodosTodoIDNotFound creates DeleteTodosTodoIDNotFound with default headers values
func NewDeleteTodosTodoIDNotFound() *DeleteTodosTodoIDNotFound {

	return &DeleteTodosTodoIDNotFound{}
}

// WithPayload adds the payload to the delete todos todo Id not found response
func (o *DeleteTodosTodoIDNotFound) WithPayload(payload *DeleteTodosTodoIDNotFoundBody) *DeleteTodosTodoIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todos todo Id not found response
func (o *DeleteTodosTodoIDNotFound) SetPayload(payload *DeleteTodosTodoIDNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodosTodoIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTodosTodoIDInternalServerErrorCode is the HTTP code returned for type DeleteTodosTodoIDInternalServerError
const DeleteTodosTodoIDInternalServerErrorCode int = 500

/*
DeleteTodosTodoIDInternalServerError delete todos todo Id internal server error

swagger:response deleteTodosTodoIdInternalServerError
*/
type DeleteTodosTodoIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *DeleteTodosTodoIDInternalServerErrorBody `json:"body,omitempty"`
}

// NewDeleteTodosTodoIDInternalServerError creates DeleteTodosTodoIDInternalServerError with default headers values
func NewDeleteTodosTodoIDInternalServerError() *DeleteTodosTodoIDInternalServerError {

	return &DeleteTodosTodoIDInternalServerError{}
}

// WithPayload adds the payload to the delete todos todo Id internal server error response
func (o *DeleteTodosTodoIDInternalServerError) WithPayload(payload *DeleteTodosTodoIDInternalServerErrorBody) *DeleteTodosTodoIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todos todo Id internal server error response
func (o *DeleteTodosTodoIDInternalServerError) SetPayload(payload *DeleteTodosTodoIDInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodosTodoIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
