name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@38ed6bf083115440d79b475442d6cf99ee450180 # v0.6.1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
