name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@adf38bd293f1ec3c4785fd09837e23c464e3eaf8 # v0.5.1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
