name: Clean docker images

on:
  # weekly cleanup schedule
  schedule:
    - cron: '14 4 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-docker-untagged:
    # Remove older untagged images (deprecated builds from master)
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
      with:
        delete-untagged: 'true'

  clean-docker-dev:
    # Remove older master builds
    needs: [ clean-docker-untagged ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
      with:
        delete-tags: 'sha-*'
        older-than: '1 year'
