name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
    paths-ignore:
      - master
      - 'hack/hugo/*'
      - .github/workflows/update-doc.yml
      - '*.md'
      - '**/*.md'


  pull_request:
    paths-ignore:
      - 'hack/hugo/*'
      - .github/workflows/update-doc.yml
      - '*.md'
      - '**/*.md'


jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test.yml@ef14d94bfba7bf45458ce6a6afd4a1c75e04ac2a # v0.4.4
    secrets: inherit
